### PR TITLE
Update Before you post an issue Readme

### PR DESCRIPTION
**Pull request by makers-mark**
Check out the bottom of it first, because it involves business decisions.

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Well, v2.3.0 is under the beta.

**Comment by makers-mark** [comment]
Sorry

**Comment by wf9a5m75** [comment]
But thank you for correcting my bad English.
Since I'm not native English speaker, I appreciate for your help.

**Comment by makers-mark** [comment]
Thank you for everything that you do and have done too. I know that English
is not native to you, and in an environment like github this can be
unnerving because of the requirements. And on top of that, you have other
people who have a totally different native language than your own, trying
to discuss or tell about issues. It gets dicey because,  I presume people
use a translator like Google, but things get lost or added in the
translation and hence the troubleshooting.

Anyways, thank you for your plugin, commitment, and knowledge.

**Pull request closed without merging**
